name: multi_pipeline
on:
    push:
        branches:
            - master
jobs:
    on-push:
        if: github.event == 'push'
        runs-on: windows-latest
        steps:
          -  name: running on master/test push
             run: echo "running on master/test push"
    